import { ArrowRight, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { mockAuctions } from '../data/auctions';
import AuctionCard from '../components/AuctionCard';

export default function Home() {
  return <>
    <section className="hero page-width"><div className="hero-copy"><div className="kicker"><span className="status-dot" /> Private by design</div><h1>Bid boldly.<br /><em>Reveal less.</em></h1><p className="hero-lede">A new standard for digital auctions. Participate with confidence while individual bids stay private until the auction is complete.</p><div className="hero-actions"><Link className="button primary" to="/auctions">Explore auctions <ArrowRight size={17} /></Link><Link className="button secondary" to="/create">Create auction</Link></div><div className="hero-note"><LockKeyhole size={15} /> Commit-reveal bidding hides bid amounts until the reveal phase.</div></div><div className="hero-art"><div className="art-label">FEATURED / 001</div><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-sculpture"><span>PA</span></div><div className="hero-art-caption"><span>Aurora in Stillness</span><small>Studio North · 1 of 1</small></div></div></section>
    <section className="principles page-width"><div className="eyebrow">The private auction protocol</div><div className="principle-grid"><div><span className="principle-icon"><LockKeyhole /></span><h3>Private by default</h3><p>Your bid remains private while the auction is active. The final result can be verified without unnecessarily exposing losing bids.</p></div><div><span className="principle-icon"><ShieldCheck /></span><h3>Verifiable outcomes</h3><p>Designed for transparent results without forcing every participant to show their hand in public.</p></div><div><span className="principle-icon"><Sparkles /></span><h3>Built for Sepolia</h3><p>A clear, calm interface for wallet connection, testnet settlement, and cryptographic bidding.</p></div></div></section>
    <section className="featured page-width"><div className="section-heading"><div><div className="eyebrow">Open now</div><h2>Find your next signal.</h2></div><Link className="text-link" to="/auctions">View all auctions <ArrowRight size={16} /></Link></div><div className="auction-grid">{mockAuctions.slice(0, 3).map((auction) => <AuctionCard key={auction.id} auction={auction} />)}</div></section>
  </>;
}
